### ISSUE TITLE
ReferenceError when a submodule can not be found

### ISSUE THREAD

**Issue by DennisAhaus** [iamchairs/snooze#46]
Hi there is bug  in lib/snooze.js

You throw an error when a submodule could not be found:

```js
throw new Error(
                'Unable to find submodule in node_modules (recursively): ' +
                submodule);
```
This ends in a ReferenceError because your variable is called `submod` and not `submodule` here.

**Comment by iamchairs** [comment]
Good catch. This would have passed the unit tests because referencing a variable that doesn't exist would throw an error and the unit test checked if an error was thrown.

Would you like to make this PR to dev?
