### ISSUE TITLE
Searching for submodules can end in error

### ISSUE THREAD

**Issue by DennisAhaus** [iamchairs/snooze#47]
When you search for dependent submodules in lib/snooze.js in method Snooze.prototype.findSubmodPath this can end in an error if the package.json of the module doesn't have a main property. 

I would expect (like node's require does) that you take a default like index.js / main.js if the main property does not exist. The error message can also be a problem because that messages says that the module does not exist but if i look inside node_modules the modules exists. This is a little bit confusing if the user does not anaylse the code :-)

if i have enough time the next days i will fix that and send a pull request

**Comment by iamchairs** [comment]
Not necessarily a bug but definitely something that makes sense to add. If you'd like to make that PR to dev we can mark an alpha.7 release for it.
